# Generated by Django 5.0.4 on 2026-09-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
